#!/usr/bin/env python3

class Contact:
    def __init__(self, first_name, business=False):
        self.business = business
        self.first_name = first_name
        self.last_name = None
        self.email = None
        self.phone_number = None
        self.notes = None
        self.social_media = { 'instagram': None, 'facebook': None }
        if not business:
            self.birthday = None

    def __str__(self):
        if self.last_name:
            return f'{self.first_name} {self.last_name}'
        else:
            return f'{self.first_name}'

c1 = Contact("fn1")
c1.last_name = "ln1"
c1.email = "em1"
c1.phone_number = "1234567890"
c1.notes = "notes 1"
c1.social_media['instagram'] = "ig1"
c1.social_media['facebook'] = "fb1"
c1.business = True

c2 = Contact("fn2")
c2.last_name = "ln2"
c2.phone_number = "1234567891"
c2.notes = "notes 2"
c2.social_media['instagram'] = "ig2"
c2.social_media['facebook'] = "fb2"

c3 = Contact("fn3")
c3.last_name = "ln3"
c3.email = "em3"
c3.notes = "notes 3"
c3.social_media['instagram'] = "ig3"
c3.social_media['facebook'] = "fb3"

c4 = Contact("fn4")
c4.last_name = "ln4"
c4.email = "em4"
c4.phone_number = "1234567893"
c4.notes = "notes 4"
c4.social_media['facebook'] = "fb4"

c5 = Contact("fn5")
c5.last_name = "ln5"
c5.email = "em5"
c5.phone_number = "1234567894"
c5.notes = "notes 5"
c5.social_media['instagram'] = "ig5"

contacts = [c1, c2, c3, c4, c5]

def exportContacts(contacts):
    
    result = 'first_name,last_name,business,email,phone,notes,instagram,facebook\n'
    delim = ','
    for contact in contacts:
        
        result += contact.first_name + delim

        if contact.last_name:
            result += contact.last_name
        result += delim

        result += str(contact.business).lower() + delim

        if contact.email:
            result += contact.email
        result += delim

        if contact.phone_number:
            result += contact.phone_number
        result += delim

        if contact.notes:
            result += '"' + contact.notes + '"'
        result += delim

        if contact.social_media['instagram']:
            result += contact.social_media['instagram']
        result += delim

        if contact.social_media['facebook']:
            result += contact.social_media['facebook']
        result += '\n'

    filepath = 'contacts-export.csv'
    fptr = open(filepath, 'w')

    fptr.write(result)
    fptr.close()

exportContacts(contacts)